name: "Deploy Request"
description: "Trigger deployment to UAT or PROD"
title: "Select the environment"
body:
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - uat
        - prod
    validations:
      required: true
